use business_data;
CREATE TABLE crop_stress_forecast_data_backup (
  crop_stress_forecast_data_backup_id bigint(20) NOT NULL auto_increment,
  crop_stress_forecast_data_id bigint(20) NOT NULL,
  crop_sown_data_id bigint(20) NOT NULL,
  village_water_available_data_id bigint(20) NOT NULL,
  model_date int(11) NOT NULL,
  crop_stage_id smallint(5) NOT NULL,
  cumm_water_supplied double DEFAULT NULL,
  optimal_water_req double DEFAULT NULL,
  minimal_water_req double DEFAULT NULL,
  owr_stress_factor_1 double DEFAULT NULL,
  owr_stress_factor_2 double DEFAULT NULL,
  owr_stress_factor_3 double DEFAULT NULL,
  owr_stress_factor_4 double DEFAULT NULL,
  mwr_stress_factor_1 double DEFAULT NULL,
  mwr_stress_factor_2 double DEFAULT NULL,
  mwr_stress_factor_3 double DEFAULT NULL,
  mwr_stress_factor_4 double DEFAULT NULL,
  owr_is_crop_under_stress tinyint(4) NOT NULL DEFAULT 0,
  mwr_is_crop_under_stress tinyint(4) NOT NULL DEFAULT 0,
  insert_ts bigint(20) NOT NULL,
  update_ts bigint(20) DEFAULT NULL,
  deleted tinyint(4) NOT NULL DEFAULT 0,
  user_session_id bigint(20) NOT NULL,
  pest_names varchar(255) DEFAULT NULL,
  owr_next_7_days double DEFAULT NULL,
  mwr_next_7_days double DEFAULT NULL,
  water_available_next_7_days double DEFAULT NULL,
  last_n_days_computed_asm varchar(255) DEFAULT NULL,
  crop_sown_data_source int(11) DEFAULT 0 COMMENT 'this field value 0 indicate the Farm_Data_id has placed in crop_sown_data field.1 Indicate crop_sown_data table id places in crop_sown_data_id',
  primary key(crop_stress_forecast_data_backup_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='It is a backup table';